apiVersion: v1
kind: Namespace
metadata:
  name: portainer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: portainer-agent-sa
  namespace: portainer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: portainer-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: portainer-agent-sa
    namespace: portainer
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: portainer-agent
  namespace: portainer
spec:
  selector:
    matchLabels:
      app: portainer-agent
  template:
    metadata:
      labels:
        app: portainer-agent
    spec:
      serviceAccountName: portainer-agent-sa
      containers:
        - name: agent
          image: portainer/agent:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: LOG_LEVEL
              value: INFO
            - name: KUBERNETES_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: AGENT_CLUSTER_ADDR
              value: portainer-agent-headless
          ports:
            - containerPort: 9001
              name: agent
          volumeMounts:
            - name: var-run
              mountPath: /var/run
            - name: var-lib-docker
              mountPath: /var/lib/docker
              readOnly: true
      volumes:
        - name: var-run
          hostPath:
            path: /var/run
        - name: var-lib-docker
          hostPath:
            path: /var/lib/docker
---
apiVersion: v1
kind: Service
metadata:
  name: portainer-agent
  namespace: portainer
spec:
  type: NodePort
  selector:
    app: portainer-agent
  ports:
    - name: agent
      port: 9001
      targetPort: 9001
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: portainer-agent-headless
  namespace: portainer
spec:
  clusterIP: None
  selector:
    app: portainer-agent
  ports:
    - name: agent
      port: 9001
      targetPort: 9001
      protocol: TCP
