apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infrastructure-base
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - clusters:
      selector:
        matchExpressions:
        - key: argocd.argoproj.io/secret-type
          operator: In
          values: [cluster]
        - key: type
          operator: NotIn
          values: [management]  # 排除 devops 集群
      values:
        # 默认值
        edgeAgentEnabled: "true"
        traefikEnabled: "true"
  template:
    metadata:
      name: 'infrastructure-{{.name}}'
      labels:
        app.kubernetes.io/managed-by: argocd
        app.kubernetes.io/part-of: infrastructure
        env: '{{.metadata.labels.env}}'
    spec:
      project: default
      source:
        repoURL: 'http://git.devops.192.168.51.30.sslip.io/fc005/devops.git'
        path: infrastructure
        targetRevision: master
        helm:
          releaseName: infrastructure
          parameters:
          - name: cluster.name
            value: '{{.name}}'
          - name: cluster.env
            value: '{{.metadata.labels.env}}'
          - name: cluster.provider
            value: '{{.metadata.labels.provider}}'
          - name: edgeAgent.enabled
            value: 'true'
          - name: edgeAgent.edgeId
            value: '{{.metadata.annotations.portainer-edge-id}}'
          - name: edgeAgent.edgeKey
            value: '{{.metadata.annotations.portainer-edge-key}}'
          - name: edgeAgent.cluster.name
            value: '{{.name}}'
          - name: edgeAgent.cluster.env
            value: '{{.metadata.labels.env}}'
          - name: edgeAgent.cluster.provider
            value: '{{.metadata.labels.provider}}'
          - name: traefik.enabled
            value: 'true'
          - name: traefik.cluster.name
            value: '{{.name}}'
          - name: traefik.cluster.env
            value: '{{.metadata.labels.env}}'
          - name: traefik.cluster.provider
            value: '{{.metadata.labels.provider}}'
      destination:
        server: '{{.server}}'
        namespace: kube-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true

